path: E:\Deep Learning & Generative AI\Projects\Yolo-V8\Yolo-V11-Object-Detection\data  # Base directory for the dataset
train: images\train  # Training images
val: images\val      # Validation images

nc : 2
names : ['cat', 'dog']
  